name: CD
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  npm:
    name: npm
    runs-on: ubuntu-22.04
    permissions:
      id-token: write # To attach provenance to the published package
    environment:
      name: npm
      url: https://www.npmjs.com/package/@ericcornelissen/bash-parser
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm clean-install
      - name: Publish to npm
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance
