name: CI
on:
  pull_request: ~
  push: ~

permissions: read-all

jobs:
  main:
    name: CI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Coverage
        run: npm run cover-test
